# Embed the static page as string literals so the server has no working-directory dependency.
file(WRITE "${OUTPUT}" "// Generated from web/; do not edit.\n#pragma once\n")
foreach(name index style api geometry controls)
    if(name STREQUAL "index")
        set(extension html)
    elseif(name STREQUAL "style")
        set(extension css)
    else()
        set(extension js)
    endif()
    file(READ "${SOURCE_DIR}/${name}.${extension}" source)
    if(source MATCHES "\\)buddha_web\"")
        message(FATAL_ERROR "Web source contains the raw string delimiter")
    endif()
    file(APPEND "${OUTPUT}" "inline const char *buddha_web_${name} = R\"buddha_web(${source})buddha_web\";\n")
endforeach()
